### ISSUE TITLE
Unhandled rejection Error: 502

### ISSUE THREAD

**Issue by KnorpelSenf** [edisonchee/slimbot#18]
I created a bot that's pretty minimal, it doesn't go much beyond the simple example.
I'm pretty new to node and I can't really explain why I'm getting the following error:

```
Unhandled rejection Error: 502:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>

    at Request.then.resp (/home/myself/src/node_modules/slimbot/src/telegram.js:43:15)
    at tryCatcher (/home/myself/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/myself/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/myself/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/myself/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/myself/src/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/myself/src/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/myself/src/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/myself/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Might this be a bug related to this project?

**Comment by KnorpelSenf** [comment]
Sure. I'm using the [simple usage example](https://github.com/edisonchee/slimbot/blob/master/examples/simpleUsage.js) from this repo. You might be able to reproduce the error using your local machine, but since my bot is running on a server from [zeit.co](https://zeit.co/now) and I can't exactly figure out how to get that error on my local machine, I'll just share with you exactly what I did:

1. Create a file with the code from the given example file. Insert the line `require('http').createServer().listen(3000);` somewhere in the beginning or so, line 3 perhaps. This seems to be required by zeit.co to keep the instance running.
2. Create a file called "now.json" in the same directory with the following content:
```
{
    "env": {
        "TELEGRAM_BOT_TOKEN": "@my-api-token"
    },
    "scale": {
        "bru1": {
            "min": 1,
            "max": 1
        }
    }
}
```
3. Create yet another file, this one is called "package.json" and it has the following content:
```
{
    "name": "my-bot",
    "version": "0.2.0",
    "dependencies": {
        "slimbot": "latest",
        "dotenv": "latest"
    },
    "scripts": {
        "start": "node simpleUsage.js"
    }
}
```
4. Install the npm package "now" and sign in to now. This should work with `npm i -g now` followed by `now login`.
5. Set a now secret for the API key using `now secrets add my-api-token "XXXXX"` and replace XXXXX by your API token generated from [BotFather](https://t.me/botfather).
6. Deploy the bot using `now`.
7. Send a message to the bot. Unfortunately, I'm unable to specify further details on how to reproduce the error. Let the bot run for a few days and _it should happen_.

**Comment by edisonchee** [comment]
@KnorpelSenf you're getting an error because of a fault with Telegram servers. The error you're getting is thrown here:
https://github.com/edisonchee/slimbot/blob/d075315cdba1195451bb2b3a510a9d2b4351aaae/src/telegram.js#L43
Your bot was sending a request to their API and it simply returned a 502.

**Comment by KnorpelSenf** [comment]
So I simply catch it and everything is fine? That was too easy … sorry for bothering such a beginner question, I didn't know better.

**Comment by edisonchee** [comment]
No worries :)
