### ISSUE TITLE
Error when sending Message

### ISSUE THREAD

**Issue by Daniele-Tentoni** [edisonchee/slimbot#38]
Hi all, I'm using Firebase and Slimbot with webhook.
I call first the function `const slimbot = new Slimbot("<<my_token>>")`
Then, when i do `slimbot.sendMessage(chat_id, "<<my_message>>")`, i receive:
```
RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at new RequestError (/srv/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/srv/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/srv/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/srv/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/srv/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

Can you help me? Do you need more logs?

**Comment by edisonchee** [comment]
@Daniele-Tentoni seems like a Firebase issue. Check out [this Stackoverflow thread](https://stackoverflow.com/questions/56066659/some-error-occures-after-send-request-to-the-function-url).

The error `getaddrinfo EA_AGAIN api.telegram.org:443` means a DNS lookup failed for the hostname `api.telegram.org`.

**Comment by edisonchee** [comment]
Closing due to lack of inactivity in 2 weeks.
