### ISSUE TITLE
Please provide a Telegram bot token when instantiating

### ISSUE THREAD

**Issue by Karam-DEV** [edisonchee/slimbot#40]
```
/data/data/com.termux/files/home/node/node_modules/slimbot/src/telegram.js:11
      throw new Error('Please provide a Telegram bot token when instantiating');
      ^

Error: Please provide a Telegram bot token when instantiating
    at new <anonymous> (/data/data/com.termux/files/home/node/node_modules/slimbot/src/telegram.js:11:13)
    at new Slimbot (/data/data/com.termux/files/home/node/node_modules/slimbot/src/slimbot.js:8:5)
    at Object.<anonymous> (/data/data/com.termux/files/home/node/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11
```

**And my code is** 

```
const Slimbot = require('slimbot');
const slimbot = new Slimbot(process.env["1085044735:AAHwW_YNHpDx5ppLWp5JkreO7EFNp9UGERR"]);

// Register listeners
slimbot.on('message', message => {
  // reply when user sends a message
  slimbot.sendMessage(message.chat.id, 'Message received');
});

slimbot.on('edited_message', edited_message => {
  // reply when user edits a message
  slimbot.sendMessage(edited_message.chat.id, 'Message edited');
});

// Call API
slimbot.startPolling();

console.log('polling...');

setTimeout(() => {
  slimbot.stopPolling();
}, 10000);``
```

**Comment by fax1ty** [comment]
Something tells me that you don't have such a variable in process.env like `1085044735:AAHwW_YNHpDx5ppLWp5JkreO7EFNp9UGERR`. You're using a real API key. The example had a variable in mind. Just replace `process.env["1085044735:AAHwW_YNHpDx5ppLWp5JkreO7EFNp9UGerr"]` to `"1085044735:AAHwW_YNHpDx5ppLWp5JkreO7EFNp9UGerr"`

**Comment by edisonchee** [comment]
Seems like I should change the example and documentation. This isn't the first time people had trouble with the bot token. 🤔

**Comment by edisonchee** [comment]
Decided to leave it as it is to encourage using environment variables when it comes to API tokens, closing this issue for now unless someone else thinks otherwise.
