### ISSUE TITLE
Error during slimbot.sendPhoto call

### ISSUE THREAD

**Issue by timmyyy** [edisonchee/slimbot#44]
Hi, I'm trying slimbot to test the scenario:
1. I write to the bot
2. It sends me an image in response

code:
```javascript
const Slimbot = require( "slimbot" )
const fs = require( "fs" )

const socks5proxy = {
    socksHost: "174.0.79.91",
    socksPort: "9999"
}
const slimbot = new Slimbot( "<API_TOKEN>", socks5proxy )

let fileUpload = fs.createReadStream( __dirname + "/../example.png" )

slimbot.on( "message", ( message ) => {
    slimbot.sendPhoto( message.chat.id, fileUpload ).then( message => {
        console.log( message.result.photo )
    } )

} )

slimbot.startPolling()
```

versions:
"slimbot": "^4.8.0"
node: v14.3.0

But it crashes with this message
```
_http_outgoing.js:802
    this.socket._writableState.corked = 1;
                                      ^

TypeError: Cannot set property 'corked' of undefined
    at ClientRequest.end (_http_outgoing.js:802:39)
    at Request.end (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/request/request.js:1508:14)
    at FormData.onend (internal/streams/legacy.js:46:10)
    at FormData.emit (events.js:327:22)
    at FormData.CombinedStream.end (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/combined-stream/lib/combined_stream.js:163:8)
    at FormData.CombinedStream._realGetNext (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/combined-stream/lib/combined_stream.js:94:10)
    at FormData.CombinedStream._getNext (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/combined-stream/lib/combined_stream.js:82:12)
    at DelayedStream.emit (events.js:327:22)
    at DelayedStream._handleEmit (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/delayed-stream/lib/delayed_stream.js:82:15)
    at ReadStream.source.emit (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/delayed-stream/lib/delayed_stream.js:29:19)
    at ReadStream.source.emit (/Users/tznasibullin/IdeaProjects/gh/mosru-checker/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)

```

When instead of slimbot.sendPhoto I try 
```javascript
slimbot.sendMessage( message.chat.id, "Message received" )
```
 it works perfectly well

**Comment by Haqverdi** [comment]
Have you tried without streams?

**Comment by timmyyy** [comment]
> Have you tried without streams?

Yes, but
1. That's not how it's supposed to work according to [examples](https://github.com/edisonchee/slimbot/blob/master/examples/sendFile.js)
2. If I try fs.readFileSync then slimbot follows this code 
```JavaScript
sendPhoto(chatId, photo, optionalParams, callback) {
    let params;
    let formData;
  
    if (isReadableStream(photo)) {
      params = {
        chat_id: chatId
      };
      formData = {
        photo: photo
      };
    } else {
      params = {
        chat_id: chatId,
        photo: photo
      };
    }

    if (typeof optionalParams == 'function') {
      callback = optionalParams;
    } else {
      Object.assign(params, optionalParams);
    }

    return this._request('sendPhoto', params, formData, callback);
  }
```

and sets a Buffer object (result of fs.readFileSync) to "photo" field, that represents query param in Request, but In order to upload a file afaic it must be in "formData" field, that is only possible when Stream is used.
As a result telegram server responds with "414 Request-URI Too Large".

**Comment by edisonchee** [comment]
Hi @timmyyy, thanks for bringing this up. After some digging around it seems like a core library issue with Slimbot. Currently all requests to Telegram Bot API are made via `GET`, and long query information in a request will result in a `414` error as [described here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15). 

A quick fix for the library now would be to detect for `formData` and set the request method to `POST`. Any thoughts?
